name: jsony
description: A lightweight package to easily export and import class members in json format.
version: 1.0.0
repository: https://github.com/alierkanimrek/jasony

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
